repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
    - id: ruff
      args: [
        "--select=I",
        "--fix"
      ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'
  hooks:
  -   id: mypy
      args: [
        --ignore-missing-imports,
        --disable-error-code=import-untyped
      ] 